base_url = "https://www.mygov.in/covid-19"
tc_title = "COVID19 STATEWISE STATUS | MyGov.in"
sl_total_confirmed = "//*[@id='node-287111']/div/div[8]/div/div[2]/div[position]/div/div/div/div[1]/div[2]/div"
sl_stateName = "//*[@id='node-287111']/div/div[8]/div/div[2]/div[position]/div/div/div/div[2]/div[2]/div"
sl_discharged = "//*[@id='node-287111']/div/div[8]/div/div[2]/div[position]/div/div/div/div[3]/div[2]/div"
sl_death = "//*[@id='node-287111']/div/div[8]/div/div[2]/div[position]/div/div/div/div[4]/div[2]/div"
sl_no_of_states = "//*[@id='node-287111']/div/div[8]/div/div[2]/div"
sl_list_of_statePresence = "//*[@id='node-287111']/div/div[8]/div/div[2]"
mp_activeCases = "//*[@id='#dashboard']/div[2]/div/span"
mp_discharged = "//*[@id='#dashboard']/div[3]/div/span"
mp_death = "//*[@id='#dashboard']/div[4]/div/span"
mp_migrated = "//*[@id='#dashboard']/div[5]/div/span"
mp_stateLevelStatus = "outerlink"
